from requests import get
print('==========================================')
ip = input('Digite o endereço IP: ')
print('==========================================')
log = get('https://ipapi.co/'+ip+'/json/')
try:
    log.raise_for_status()
except Exception as e:
    print('Error: ', e)
else:
    data = log.json()
    print('Eendereço IP: ', data['ip'])
    print('==========================================')
    print('Provedor: ', data['org'])
    print('==========================================')
    print('ASN: ', data['asn'])
    print('==========================================')
    print('Cidade: ', data['city'])
    print('==========================================')
    print('Região: ', data['region'])
    print('==========================================')
    print('Sigla da região: ', data['region_code'])
    print('==========================================')
    print('Pais: ', data['country_name'])
    print('==========================================')
    print('Sigla do país: ', data['country'])
    print('==========================================')
    print('Código ISO: ', data['country_code_iso3'])
    print('==========================================')
    print('Capital do pais: ', data['country_capital'])
    print('==========================================')
    print('Registro de dominio: ', data['country_tld'])
    print('==========================================')
    print('Código zip: ', data['postal'])
    print('==========================================')
    print('Latitude: ', data['latitude'])
    print('==========================================')
    print('Longitude: ', data['longitude'])
    print('==========================================')
    print('Zona: ', data['timezone'])
    print('==========================================')
    print('Código de discagem do pais: ', data['country_calling_code'])
    print('==========================================')
    print('Moeda: ', data['currency'] , '(', data['currency_name'], ')')
    print('==========================================')
    print('Idioma: ', data['languages'])
    print('==========================================')
    print('Extensão territorial (Área): ', data['country_area'])
    print('==========================================')
    print('População: ', data['country_population'])
    print('==========================================')
